# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d78f0d269804d44e38317a8f6dfb13f0969f2ca5853e1676d2a5a0a533cffdee74f60822696cbcd72deb6f6b96d9bd3849a05333773cbe39d06463894026baab

test:
  secret_key_base: f7fa999c6a446b17b9ba4ff3a9017984eac071e5e214533e309f6fdb256f8c8e0b9404b0235476589d6bc68fae8de5a76c8271cf163a1c6ea58c5947af5c149c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
